<<<<<<< HEAD
services:
  - type: web
    name: hamyar-hoosh-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
=======
services:
  - type: web
    name: hamyar-hoosh-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
>>>>>>> 193021b6980fc1f552e28a237a67d4ba76fc1b9f
    healthCheckPath: "/"